const data = {
  breakfast: {
    starch: [
      {
        id: 1,
        title: "Oat",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 2,
        title: "Whole grains bread",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 13,
        title: "Rice Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Pasta Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 27,
        title: "Quinoa Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Corn",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Potato",
        amount: "90 G",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
    ],
    meat: [
      {
        id: 3,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 15,
        title: "Chicken breast",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 16,
        title: "Fish (tuna, tilapia, salmon, shrimp, crab, mackerel)",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 17,
        title: "Lean Beef",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 30,
        title: "Liver, heart, kidneys",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 35,
        title: "Cottage Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    milk: [
      {
        id: 4,
        title: "Low-fat milk",
        amount: "1 CUP (240 ML)",
        amountInt: 240,
        amountType: "ML",
        selected: false,
      },
    ],
    fruits: [
      {
        id: 5,
        title: "Banana",
        amount: "1 (4 OZ)",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Apple",
        amount: "1 (4 OZ)",
        amountInt: 4,
        amountType: "piece",
        selected: false,
      },
      {
        id: 12,
        title: "Fruit Juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 22,
        title: "Strawberries",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 23,
        title: "Blackberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 24,
        title: "Blueberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Guava",
        amount: "1/2",
        amountInt: 0.5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
    ],
  },

  snack1: {
    fruits: [
      {
        id: 5,
        title: "Banana",
        amount: "1 (4 OZ)",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Apple",
        amount: "1 (4 OZ)",
        amountInt: 4,
        amountType: "piece",
        selected: false,
      },
      {
        id: 12,
        title: "Fruit Juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 22,
        title: "Strawberries",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 23,
        title: "Blackberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 24,
        title: "Blueberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Guava",
        amount: "1/2",
        amountInt: 0.5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
    ],
    milk: [
      {
        id: 21,
        title: "Yogurt",
        amount: "180 G",
        amountInt: 180,
        amountType: "G",
        selected: false,
      },
      {
        id: 4,
        title: "Low-fat milk",
        amount: "1 CUP (240 ML)",
        amountInt: 240,
        amountType: "ML",
        selected: false,
      },
    ],
  },

  lunch: {
    starch: [
      {
        id: 1,
        title: "Oat",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 2,
        title: "Whole grains bread",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 13,
        title: "Rice Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Pasta Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 27,
        title: "Quinoa Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Corn",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Potato",
        amount: "90 G",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
    ],
    meat: [
      {
        id: 3,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 35,
        title: "Cottage Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 15,
        title: "Chicken breast",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 16,
        title: "Fish (tuna, tilapia, salmon, shrimp, crab, mackerel)",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 17,
        title: "Lean Beef",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 30,
        title: "Liver, heart, kidneys",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetable: [
      {
        id: 18,
        title: "Cooked vegetables (except potato, peas, taro)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 31,
        title: "Raw vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 32,
        title: "Vegetables juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 6,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 7,
        title: "Cashews",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 8,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 9,
        title: "Peanuts",
        amount: "10",
        amountInt: 10,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Olive oil / Canola oil",
        amount: "1 TSP",
        amountInt: 1,
        amountType: "TSP",
        selected: false,
      },
      {
        id: 20,
        title: "Olive",
        amount: "8",
        amountInt: 8,
        amountType: "piece",
        selected: false,
      },
      {
        id: 33,
        title: "Avocado medium",
        amount: "2 TBSP",
        amountInt: 2,
        amountType: "TBSP",
        selected: false,
      },
      {
        id: 34,
        title: "Chia seeds, Flaxseeds, Sesame",
        amount: "C",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
  },

  snack2: {
    milk: [
      {
        id: 21,
        title: "Yogurt",
        amount: "180 G",
        amountInt: 180,
        amountType: "G",
        selected: false,
      },
      {
        id: 4,
        title: "Low-fat milk",
        amount: "1 CUP (240 ML)",
        amountInt: 240,
        amountType: "ML",
        selected: false,
      },
    ],
    fruits: [
      {
        id: 5,
        title: "Banana",
        amount: "1 (4 OZ)",
        amountInt: 4,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Apple",
        amount: "1 (4 OZ)",
        amountInt: 4,
        amountType: "piece",
        selected: false,
      },
      {
        id: 12,
        title: "Fruit Juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 22,
        title: "Strawberries",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 23,
        title: "Blackberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 24,
        title: "Blueberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Guava",
        amount: "1/2",
        amountInt: 0.5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
    ],
    meat: [
      {
        id: 3,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 35,
        title: "Cottage Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 15,
        title: "Chicken breast",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 16,
        title: "Fish",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 17,
        title: "Lean Beef",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 30,
        title: "Liver, heart, kidneys",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetable: [
      {
        id: 18,
        title: "Cooked vegetables (except potato, peas, taro)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 31,
        title: "Raw vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 32,
        title: "Vegetables juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 6,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 7,
        title: "Cashews",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 8,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 9,
        title: "Peanuts",
        amount: "10",
        amountInt: 10,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Olive oil / Canola oil",
        amount: "1 TSP",
        amountInt: 1,
        amountType: "TSP",
        selected: false,
      },
      {
        id: 20,
        title: "Olive",
        amount: "8",
        amountInt: 8,
        amountType: "piece",
        selected: false,
      },
      {
        id: 33,
        title: "Avocado medium",
        amount: "2 TBSP",
        amountInt: 2,
        amountType: "TBSP",
        selected: false,
      },
      {
        id: 34,
        title: "Chia seeds, Flaxseeds, Sesame",
        amount: "C",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
  },

  dinner: {
    milk: [
      {
        id: 21,
        title: "Yogurt",
        amount: "180 G",
        amountInt: 180,
        amountType: "G",
        selected: false,
      },
      {
        id: 4,
        title: "Low-fat milk",
        amount: "1 CUP (240 ML)",
        amountInt: 240,
        amountType: "ML",
        selected: false,
      },
    ],
    starch: [
      {
        id: 1,
        title: "Oat",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 2,
        title: "Whole grains bread",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 13,
        title: "Rice Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Pasta Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 27,
        title: "Quinoa Cooked",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Corn",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Potato",
        amount: "90 G",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
    ],
    meat: [
      {
        id: 3,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 35,
        title: "Cottage Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 15,
        title: "Chicken breast",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 16,
        title: "Fish",
        amount: "1 OZ",
        amountInt: 1,
        amountType: "OZ",
        selected: false,
      },
      {
        id: 17,
        title: "Lean Beef",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 30,
        title: "Liver, heart, kidneys",
        amount: "1 OZ (30 G)",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetable: [
      {
        id: 18,
        title: "Cooked vegetables (except potato, peas, taro)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 31,
        title: "Raw vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 32,
        title: "Vegetables juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 6,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 7,
        title: "Cashews",
        amount: "6",
        amountInt: 6,
        amountType: "piece",
        selected: false,
      },
      {
        id: 8,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 9,
        title: "Peanuts",
        amount: "10",
        amountInt: 10,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Olive oil / Canola oil",
        amount: "1 TSP",
        amountInt: 1,
        amountType: "TSP",
        selected: false,
      },
      {
        id: 20,
        title: "Olive",
        amount: "8",
        amountInt: 8,
        amountType: "piece",
        selected: false,
      },
      {
        id: 33,
        title: "Avocado medium",
        amount: "2 TBSP",
        amountInt: 2,
        amountType: "TBSP",
        selected: false,
      },
      {
        id: 34,
        title: "Chia seeds, Flaxseeds, Sesame",
        amount: "C",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fruits: [
      {
        id: 5,
        title: "Banana",
        amount: "1 (4 OZ)",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Apple",
        amount: "1 (4 OZ)",
        amountInt: 4,
        amountType: "piece",
        selected: false,
      },
      {
        id: 12,
        title: "Fruit Juice",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 22,
        title: "Strawberries",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 23,
        title: "Blackberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 24,
        title: "Blueberries",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Guava",
        amount: "1/2",
        amountInt: 0.5,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
    ],
  },
};

export default data;
