const data = {
  breakfast: {
    starch: [
      {
        id: 1,
        title: "Bread",
        amount: "1 slice",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 2,
        title: "Whole Grain Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 3,
        title: "White Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 4,
        title: "Oat (uncooked)",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 5,
        title: "Oat (cooked)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 6,
        title: "Granola",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 7,
        title: "Pasta (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 8,
        title: "Rice (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 9,
        title: "Bagel",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Tortilla",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Quinoa (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 12,
        title: "Potato with skin",
        amount: "1/4 large (90 G)",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
      {
        id: 13,
        title: "Potato (boiled)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Mashed Potato",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 15,
        title: "Rice Cakes",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
    ],
    fruit: [
      {
        id: 16,
        title: "Apple",
        amount: "1 small",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 17,
        title: "Apricots",
        amount: "4 whole",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 18,
        title: "Banana",
        amount: "1 regular",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Blueberries",
        amount: "2/4 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 20,
        title: "Cantaloupe",
        amount: "1 CUP cubed",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 21,
        title: "Cherries (fresh)",
        amount: "12",
        amountInt: 12,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 22,
        title: "Guava",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 23,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 24,
        title: "Mango (small)",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Orange (small)",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Dates",
        amount: "3",
        amountInt: 3,
        amountType: "pieces",
        selected: false,
      },
    ],
    dairy: [
      {
        id: 27,
        title: "Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Skim Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Coconut Milk (light)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 30,
        title: "Yogurt or Greek Yogurt",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 31,
        title: "Olive Oil",
        amount: "1 tsp",
        amountInt: 1,
        amountType: "tsp",
        selected: false,
      },
      {
        id: 32,
        title: "Walnuts",
        amount: "4 halves",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 33,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 34,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 35,
        title: "Mixed Nuts",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 36,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "pieces",
        selected: false,
      },
    ],
    meat: [
      {
        id: 37,
        title: "Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 38,
        title: "White Egg",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 39,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 40,
        title: "Cottage Cheese",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 41,
        title: "Beef",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 42,
        title: "Fish",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 43,
        title: "Salmon",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 44,
        title: "Chicken",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 45,
        title: "Turkey",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 46,
        title: "Liver",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetables: [
      {
        id: 47,
        title: "Raw Vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 48,
        title: "Cooked Vegetables",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
  },
  snack1: {
    starch: [
      {
        id: 1,
        title: "Bread",
        amount: "1 slice",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 2,
        title: "Whole Grain Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 3,
        title: "White Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 4,
        title: "Oat (uncooked)",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 5,
        title: "Oat (cooked)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 6,
        title: "Granola",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 7,
        title: "Pasta (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 8,
        title: "Rice (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 9,
        title: "Bagel",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Tortilla",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Quinoa (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 12,
        title: "Potato with skin",
        amount: "1/4 large (90 G)",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
      {
        id: 13,
        title: "Potato (boiled)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Mashed Potato",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 15,
        title: "Rice Cakes",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
    ],
    fruit: [
      {
        id: 16,
        title: "Apple",
        amount: "1 small",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 17,
        title: "Apricots",
        amount: "4 whole",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 18,
        title: "Banana",
        amount: "1 regular",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Blueberries",
        amount: "2/4 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 20,
        title: "Cantaloupe",
        amount: "1 CUP cubed",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 21,
        title: "Cherries (fresh)",
        amount: "12",
        amountInt: 12,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 22,
        title: "Guava",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 23,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 24,
        title: "Mango (small)",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Orange (small)",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Dates",
        amount: "3",
        amountInt: 3,
        amountType: "pieces",
        selected: false,
      },
    ],
    dairy: [
      {
        id: 27,
        title: "Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Skim Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Coconut Milk (light)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 30,
        title: "Yogurt or Greek Yogurt",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 31,
        title: "Olive Oil",
        amount: "1 tsp",
        amountInt: 1,
        amountType: "tsp",
        selected: false,
      },
      {
        id: 32,
        title: "Walnuts",
        amount: "4 halves",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 33,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 34,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 35,
        title: "Mixed Nuts",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 36,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "pieces",
        selected: false,
      },
    ],
    meat: [
      {
        id: 37,
        title: "Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 38,
        title: "White Egg",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 39,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 40,
        title: "Cottage Cheese",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 41,
        title: "Beef",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 42,
        title: "Fish",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 43,
        title: "Salmon",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 44,
        title: "Chicken",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 45,
        title: "Turkey",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 46,
        title: "Liver",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetables: [
      {
        id: 47,
        title: "Raw Vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 48,
        title: "Cooked Vegetables",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
  },
  lunch: {
    starch: [
      {
        id: 1,
        title: "Bread",
        amount: "1 slice",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 2,
        title: "Whole Grain Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 3,
        title: "White Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 4,
        title: "Oat (uncooked)",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 5,
        title: "Oat (cooked)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 6,
        title: "Granola",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 7,
        title: "Pasta (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 8,
        title: "Rice (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 9,
        title: "Bagel",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Tortilla",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Quinoa (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 12,
        title: "Potato with skin",
        amount: "1/4 large (90 G)",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
      {
        id: 13,
        title: "Potato (boiled)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Mashed Potato",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 15,
        title: "Rice Cakes",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
    ],
    fruit: [
      {
        id: 16,
        title: "Apple",
        amount: "1 small",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 17,
        title: "Apricots",
        amount: "4 whole",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 18,
        title: "Banana",
        amount: "1 regular",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Blueberries",
        amount: "2/4 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 20,
        title: "Cantaloupe",
        amount: "1 CUP cubed",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 21,
        title: "Cherries (fresh)",
        amount: "12",
        amountInt: 12,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 22,
        title: "Guava",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 23,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 24,
        title: "Mango (small)",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Orange (small)",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Dates",
        amount: "3",
        amountInt: 3,
        amountType: "pieces",
        selected: false,
      },
    ],
    dairy: [
      {
        id: 27,
        title: "Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Skim Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Coconut Milk (light)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 30,
        title: "Yogurt or Greek Yogurt",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 31,
        title: "Olive Oil",
        amount: "1 tsp",
        amountInt: 1,
        amountType: "tsp",
        selected: false,
      },
      {
        id: 32,
        title: "Walnuts",
        amount: "4 halves",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 33,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 34,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 35,
        title: "Mixed Nuts",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 36,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "pieces",
        selected: false,
      },
    ],
    meat: [
      {
        id: 37,
        title: "Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 38,
        title: "White Egg",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 39,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 40,
        title: "Cottage Cheese",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 41,
        title: "Beef",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 42,
        title: "Fish",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 43,
        title: "Salmon",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 44,
        title: "Chicken",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 45,
        title: "Turkey",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 46,
        title: "Liver",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetables: [
      {
        id: 47,
        title: "Raw Vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 48,
        title: "Cooked Vegetables",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
  },
  snack2: {
    starch: [
      {
        id: 1,
        title: "Bread",
        amount: "1 slice",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 2,
        title: "Whole Grain Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 3,
        title: "White Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 4,
        title: "Oat (uncooked)",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 5,
        title: "Oat (cooked)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 6,
        title: "Granola",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 7,
        title: "Pasta (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 8,
        title: "Rice (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 9,
        title: "Bagel",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Tortilla",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Quinoa (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 12,
        title: "Potato with skin",
        amount: "1/4 large (90 G)",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
      {
        id: 13,
        title: "Potato (boiled)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Mashed Potato",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 15,
        title: "Rice Cakes",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
    ],
    fruit: [
      {
        id: 16,
        title: "Apple",
        amount: "1 small",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 17,
        title: "Apricots",
        amount: "4 whole",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 18,
        title: "Banana",
        amount: "1 regular",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Blueberries",
        amount: "2/4 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 20,
        title: "Cantaloupe",
        amount: "1 CUP cubed",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 21,
        title: "Cherries (fresh)",
        amount: "12",
        amountInt: 12,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 22,
        title: "Guava",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 23,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 24,
        title: "Mango (small)",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Orange (small)",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Dates",
        amount: "3",
        amountInt: 3,
        amountType: "pieces",
        selected: false,
      },
    ],
    dairy: [
      {
        id: 27,
        title: "Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Skim Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Coconut Milk (light)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 30,
        title: "Yogurt or Greek Yogurt",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 31,
        title: "Olive Oil",
        amount: "1 tsp",
        amountInt: 1,
        amountType: "tsp",
        selected: false,
      },
      {
        id: 32,
        title: "Walnuts",
        amount: "4 halves",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 33,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 34,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 35,
        title: "Mixed Nuts",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 36,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "pieces",
        selected: false,
      },
    ],
    meat: [
      {
        id: 37,
        title: "Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 38,
        title: "White Egg",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 39,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 40,
        title: "Cottage Cheese",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 41,
        title: "Beef",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 42,
        title: "Fish",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 43,
        title: "Salmon",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 44,
        title: "Chicken",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 45,
        title: "Turkey",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 46,
        title: "Liver",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetables: [
      {
        id: 47,
        title: "Raw Vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 48,
        title: "Cooked Vegetables",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
  },
  dinner: {
    starch: [
      {
        id: 1,
        title: "Bread",
        amount: "1 slice",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 2,
        title: "Whole Grain Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 3,
        title: "White Toast",
        amount: "1",
        amountInt: 1,
        amountType: "slice",
        selected: false,
      },
      {
        id: 4,
        title: "Oat (uncooked)",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 5,
        title: "Oat (cooked)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 6,
        title: "Granola",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 7,
        title: "Pasta (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 8,
        title: "Rice (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 9,
        title: "Bagel",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 10,
        title: "Tortilla",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 11,
        title: "Quinoa (cooked)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 12,
        title: "Potato with skin",
        amount: "1/4 large (90 G)",
        amountInt: 90,
        amountType: "G",
        selected: false,
      },
      {
        id: 13,
        title: "Potato (boiled)",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 14,
        title: "Mashed Potato",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 15,
        title: "Rice Cakes",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
    ],
    fruit: [
      {
        id: 16,
        title: "Apple",
        amount: "1 small",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 17,
        title: "Apricots",
        amount: "4 whole",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 18,
        title: "Banana",
        amount: "1 regular",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 19,
        title: "Blueberries",
        amount: "2/4 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 20,
        title: "Cantaloupe",
        amount: "1 CUP cubed",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 21,
        title: "Cherries (fresh)",
        amount: "12",
        amountInt: 12,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 22,
        title: "Guava",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 23,
        title: "Kiwi",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 24,
        title: "Mango (small)",
        amount: "3/4 CUP",
        amountInt: 0.75,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 25,
        title: "Orange (small)",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 26,
        title: "Dates",
        amount: "3",
        amountInt: 3,
        amountType: "pieces",
        selected: false,
      },
    ],
    dairy: [
      {
        id: 27,
        title: "Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 28,
        title: "Skim Milk",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 29,
        title: "Coconut Milk (light)",
        amount: "1/3 CUP",
        amountInt: 0.33,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 30,
        title: "Yogurt or Greek Yogurt",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
    ],
    fat: [
      {
        id: 31,
        title: "Olive Oil",
        amount: "1 tsp",
        amountInt: 1,
        amountType: "tsp",
        selected: false,
      },
      {
        id: 32,
        title: "Walnuts",
        amount: "4 halves",
        amountInt: 4,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 33,
        title: "Almonds",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 34,
        title: "Hazelnuts",
        amount: "5",
        amountInt: 5,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 35,
        title: "Mixed Nuts",
        amount: "6",
        amountInt: 6,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 36,
        title: "Pistachios",
        amount: "16",
        amountInt: 16,
        amountType: "pieces",
        selected: false,
      },
    ],
    meat: [
      {
        id: 37,
        title: "Cheese",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 38,
        title: "White Egg",
        amount: "2",
        amountInt: 2,
        amountType: "pieces",
        selected: false,
      },
      {
        id: 39,
        title: "Egg",
        amount: "1",
        amountInt: 1,
        amountType: "piece",
        selected: false,
      },
      {
        id: 40,
        title: "Cottage Cheese",
        amount: "1/4 CUP",
        amountInt: 0.25,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 41,
        title: "Beef",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 42,
        title: "Fish",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 43,
        title: "Salmon",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 44,
        title: "Chicken",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 45,
        title: "Turkey",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
      {
        id: 46,
        title: "Liver",
        amount: "30 G",
        amountInt: 30,
        amountType: "G",
        selected: false,
      },
    ],
    vegetables: [
      {
        id: 47,
        title: "Raw Vegetables",
        amount: "1 CUP",
        amountInt: 1,
        amountType: "CUP",
        selected: false,
      },
      {
        id: 48,
        title: "Cooked Vegetables",
        amount: "1/2 CUP",
        amountInt: 0.5,
        amountType: "CUP",
        selected: false,
      },
    ],
  },
};
